export const APROPOS_DATA = {
  headerLabel: "À PROPOS",
  headerTitle: "Qui je suis.",
  bio: "Spécialisé dans le développement desktop (client lourd), je combine une expertise desktop solide ainsi que des compétences fullstack.",
  parcoursSectionTitle: "Parcours",
  skills: {
    "Web Frontend": ["React", "Three.js", "Angular", "Tailwind"],
    "Web Backend": ["C# ASP.NET",  "PostgreSQL", "Entity Framework Core", "SQL Server", "SQLite"],
    // "Mobile": ["Flutter", "Dart"],
    "Logiciel": ["WPF", "C#", "XAML", "ToolBook"],
    "Expertise": [".Net", "Architecture Logicielle", "Client Lourd", "Applications Métier"],
  },
  parcours: [
    {
      id: "acc-2022-1",
      year: 2022,
      title: "Baccalauréat général",
      desc: "Validation du baccalauréat Option Maths et NSI.",
      branch: "main",
    },
    {
      id: "acc-2023-1",
      year: 2023,
      title: "1er stage Actulog",
      desc: "Première immersion chez Actulog (1 mois). Découverte du développement Client Lourd WPF sur un ERP métier pour cartonniers façonneurs.",
      branch: "main",
    },
    {
      id: "acc-2023-2",
      year: 2023,
      title: "2ème stage Actulog",
      desc: "Deuxième immersion chez Actulog (2 mois). Approfondissement des connaissances en développement WPF ainsi que en architecture logicielle.",
      branch: "main",
    },
    {
      id: "acc-2024-1",
      year: 2024,
      title: "Obtention du BTS SIO",
      desc: "Validation du BTS SIO option SLAM .",
      branch: "main",
    },
    {
      id: "acc-2024-2",
      year: "oct 2024 - fév 2026",
      title: "Alternance B3 / M1",
      desc: "Alternance ~2 ans chez Actulog en tant que développeur à part entière. Migration MVVM complète, développement fullstack sur tous les modules ERP.",
      branch: "left",
    },
    {
      id: "acc-2025-1",
      year: 2025,
      title: "Obtention du Bachelor",
      desc: "Validation du Bachelor 3 à Ynov Campus Bordeaux.",
      branch: "right",
    },
    {
      id: "acc-2026-2",
      year: 2026,
      title: "Master 1",
      desc: "En cours d'année.",
      branch: "right",
    },
  ],
};
